/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyNativeMethods */

#ifndef _Included_MyNativeMethods
#define _Included_MyNativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyNativeMethods
 * Method:    pumpThoseNumbers
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_MyNativeMethods_pumpThoseNumbers
  (JNIEnv *, jobject, jint);

/*
 * Class:     MyNativeMethods
 * Method:    isMyParamFalse
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_MyNativeMethods_isMyParamFalse
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     MyNativeMethods
 * Method:    sayMyName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyNativeMethods_sayMyName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
